# Github Actions configuration file
name: Build

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            package: ZIP
            configure_args: "-DPORTABLE=ON"

          - os: ubuntu-22.04
            package: ZIP
            configure_args: "-DPORTABLE=ON"

          - os: macos-13
            package: ZIP
            configure_args: "-DPORTABLE=ON"

          - os: macos-14
            package: ZIP
            configure_args: "-DPORTABLE=ON -DCPACK_SYSTEM_NAME=Darwin-arm64"

          - os: ubuntu-22.04
            package: DEB

          - os: ubuntu-22.04
            package: RPM            

    steps:
    - name: Setup Windows/MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_INSTALL_PREFIX=dist ${{matrix.config.configure_args}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Install
      run: cmake --install ${{github.workspace}}/build --config Release
    - name: Package
      run: cpack -G ${{ matrix.config.package }} --config ${{github.workspace}}/build/CPackConfig.cmake

    - name: Upload to Github release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.zip;*.tar.gz;*.deb;*.rpm"
        tags: true
        draft: false
